
## Gopkg.toml example (these lines may be deleted)

## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
# required = ["github.com/user/thing/cmd/thing"]

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
# ignored = ["github.com/user/project/badpkg"]

## Dependencies define constraints on dependent projects. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
# [[dependencies]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"

## Overrides have the same structure as [[dependencies]], but supercede all
## [[dependencies]] declarations from all projects. Only the current project's
## [[overrides]] are applied.
##
## Overrides are a sledgehammer. Use them only as a last resort.
# [[overrides]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Optional: specifying a version constraint override will cause all other
## constraints on this project to be ignored; only the overriden constraint
## need be satisfied.
## Again, only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: specifying an alternate source location as an override will
## enforce that the alternate location is used for that project, regardless of
## what source location any dependent projects specify.
# source = "https://github.com/myfork/package.git"



[[dependencies]]
  name = "cloud.google.com/go"
  version = ">=0.7.0, <1.0.0"

[[dependencies]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "^10.0.2-beta"

[[dependencies]]
  name = "github.com/Azure/go-autorest"
  version = "^8.0.0"

[[dependencies]]
  name = "github.com/davecgh/go-spew"
  version = "^1.1.0"

[[dependencies]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.0.0"

[[dependencies]]
  name = "github.com/docker/distribution"
  version = "^2.6.1"

[[dependencies]]
  name = "github.com/docker/engine-api"
  version = ">=0.4.0, <1.0.0"

[[dependencies]]
  name = "github.com/emicklei/go-restful-swagger12"
  version = "^1.0.1"

[[dependencies]]
  branch = "master"
  name = "github.com/exponent-io/jsonpath"

[[dependencies]]
  name = "github.com/ghodss/yaml"
  version = "^1.0.0"

[[dependencies]]
  name = "github.com/go-ini/ini"
  version = "^1.27.0"

[[dependencies]]
  name = "github.com/gogo/protobuf"
  version = ">=0.4.0, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/golang/glog"

[[dependencies]]
  branch = "master"
  name = "github.com/golang/groupcache"

[[dependencies]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[dependencies]]
  name = "github.com/jmespath/go-jmespath"
  version = ">=0.2.2, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/joyent/triton-go"

[[dependencies]]
  name = "github.com/mesos/mesos-go"
  version = ">=0.0.2, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/rackspace/gophercloud"

[[dependencies]]
  name = "github.com/rancher/go-rancher"
  version = ">=0.1.0, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/rubiojr/go-vhd"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[dependencies]]
  branch = "master"
  name = "github.com/ugorji/go"

[[dependencies]]
  name = "github.com/vmware/govmomi"
  version = ">=0.14.0, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/vmware/photon-controller-go-sdk"

[[dependencies]]
  name = "github.com/xanzy/go-cloudstack"
  version = "^2.1.7"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/net"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[dependencies]]
  branch = "master"
  name = "google.golang.org/api"

[[dependencies]]
  name = "gopkg.in/gcfg.v1"
  version = "^1.2.0"

[[dependencies]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[dependencies]]
  branch = "master"
  name = "k8s.io/apiserver"

[[dependencies]]
  name = "k8s.io/client-go"
  version = "^3.0.0-beta.0"

[[dependencies]]
  branch = "master"
  name = "k8s.io/kubernetes"
